jtype: StableDiffusionGenerator
with:
  batch_size: 1
  height: 512
  max_n_subprompts: 8
  max_resolution: 589824 # 768x768
  n_iter: 1
  stable_path: ../stable-diffusion
  use_half: True
  width: 512
metas:
  py_modules:
    - executor.py